owner: EdwardLeks # GitHub username
repo: monitor # GitHub repository name
sites: # List of endpoints to track
  - name: DavaiKaks-API
    url: https://davaikaks-admin.herokuapp.com/admin
  - name: DavaiKaks
    url: http://www.davaikaks.ee
assignees: # Users to assign downtime issues (optional)
  - AnandChowdhary
status-website:
  baseUrl: /monitor # where "repo" is your repository name
  name: Monitor
