owner: EdwardLeks # GitHub username
repo: monitor # GitHub repository name
sites: # List of endpoints to track
  - name: Google
    url: https://www.google.com
  - name: DavaiKaks
    url: https://www.davaikaks.ee
assignees: # Users to assign downtime issues (optional)
  - AnandChowdhary
status-website:
  baseUrl: /monitor # where "repo" is your repository name
  name: Monitor
